// /lib/products.ts

export type Product = {
  title: string
  image: string
  category: 'plants' | 'planters'
}

export const products: Product[] = [
  // 🌿 PLANTS
  { title: 'Aglaonema', image: '/images/products/plants/aglaonema.webp', category: 'plants' },
  { title: 'Allocasia', image: '/images/products/plants/allocasia.webp', category: 'plants' },
  { title: 'Anthurium', image: '/images/products/plants/anthurium.webp', category: 'plants' },
  { title: 'Areca Palm', image: '/images/products/plants/areca-palm.webp', category: 'plants' },
  { title: 'Aspidistra', image: '/images/products/plants/aspidistra.webp', category: 'plants' },
  { title: 'Asplenium', image: '/images/products/plants/asplenium.webp', category: 'plants' },
  { title: 'Buxus Microphylla', image: '/images/products/plants/buxus-microphylla.webp', category: 'plants' },
  { title: 'Calathea Zebrina', image: '/images/products/plants/calatheazebrina.webp', category: 'plants' },
  { title: 'Crassula', image: '/images/products/plants/crassula.webp', category: 'plants' },
  { title: 'Croton Codium', image: '/images/products/plants/croton-codium.webp', category: 'plants' },
  { title: 'Croton Finger', image: '/images/products/plants/croton-finger.webp', category: 'plants' },
  { title: 'Croton Mix', image: '/images/products/plants/croton-mix.webp', category: 'plants' },
  { title: 'Croton Petra', image: '/images/products/plants/croton-petra.webp', category: 'plants' },
  { title: 'Cylindrical Ficus', image: '/images/products/plants/cylindrical-ficus.webp', category: 'plants' },
  { title: 'Dracaena Compacta Branched', image: '/images/products/plants/dracaena-compacta-branched.webp', category: 'plants' },
  { title: 'Dracaena Marginata Trunk', image: '/images/products/plants/dracaena-marginata-trunk.webp', category: 'plants' },
  { title: 'Dracaena Marginata', image: '/images/products/plants/dracaena-marginata.webp', category: 'plants' },
  { title: 'Dracaena Massangeana Trunk', image: '/images/products/plants/dracaena-massangeana-trunk.webp', category: 'plants' },
  { title: 'Dracaena Massangeana', image: '/images/products/plants/dracaena-massangeana.webp', category: 'plants' },
  { title: 'Dracaena Rikki', image: '/images/products/plants/dracaena-rikki.webp', category: 'plants' },
  { title: 'Dracaena Warneckei', image: '/images/products/plants/dracaena-warneckei.webp', category: 'plants' },
  { title: 'Ficus Alii', image: '/images/products/plants/ficus-alii.webp', category: 'plants' },
  { title: 'Ficus Benjamina', image: '/images/products/plants/ficus-benjamina.webp', category: 'plants' },
  { title: 'Ficus Bonsai', image: '/images/products/plants/ficus-bonsai.webp', category: 'plants' },
  { title: 'Ficus Cyathstipula', image: '/images/products/plants/ficus-cyathstipula.webp', category: 'plants' },
  { title: 'Ficus Elastica Variant', image: '/images/products/plants/ficus-elastica-2.webp', category: 'plants' },
  { title: 'Ficus Elastica', image: '/images/products/plants/ficus-elastica.webp', category: 'plants' },
  { title: 'Ficus Lyrata', image: '/images/products/plants/ficus-lyrata.webp', category: 'plants' },
  { title: 'Ficus Robusta', image: '/images/products/plants/ficus-robusta.webp', category: 'plants' },
  { title: 'Ficus Starlight', image: '/images/products/plants/ficus-starlight.webp', category: 'plants' },
  { title: 'Gardenia', image: '/images/products/plants/gardenia.webp', category: 'plants' },
  { title: 'Guzmania', image: '/images/products/plants/guzmania.webp', category: 'plants' },
  { title: 'Imperial Red', image: '/images/products/plants/imperialred.webp', category: 'plants' },
  { title: 'Kentia Palm', image: '/images/products/plants/kentia-palm.webp', category: 'plants' },
  { title: 'Lemon Stripe Branch', image: '/images/products/plants/lemonstripe-branch.webp', category: 'plants' },
  { title: 'Lemon Stripe', image: '/images/products/plants/lemonstripe.webp', category: 'plants' },
  { title: 'Maria Christina', image: '/images/products/plants/maria-christina.webp', category: 'plants' },
  { title: 'Monstera', image: '/images/products/plants/monstera.webp', category: 'plants' },
  { title: 'Nephrolepsis', image: '/images/products/plants/nephrolepsis.webp', category: 'plants' },
  { title: 'Nolina Trunk', image: '/images/products/plants/nolina-trunk.webp', category: 'plants' },
  { title: 'Pachira', image: '/images/products/plants/pachira.webp', category: 'plants' },
  { title: 'Phalaenopsis Purple', image: '/images/products/plants/phalaenopsis-purple.webp', category: 'plants' },
  { title: 'Phalaenopsis White', image: '/images/products/plants/phalaenopsis-white.webp', category: 'plants' },
  { title: 'Phoenix Palm', image: '/images/products/plants/phoneix-palm.webp', category: 'plants' },
  { title: 'Rhapis Excelsa', image: '/images/products/plants/rhapis-excelsa.webp', category: 'plants' },
  { title: 'Scandens', image: '/images/products/plants/scandens.webp', category: 'plants' },
  { title: 'Schefflera Compacta', image: '/images/products/plants/schefflera-combacta.webp', category: 'plants' },
  { title: 'Schefflera Gold Capella Netted', image: '/images/products/plants/schefflera-gold-capella-netted.webp', category: 'plants' },
  { title: 'Schefflera Gold Capella', image: '/images/products/plants/schefflera-gold-capella.webp', category: 'plants' },
  { title: 'Scindapsus Hanging', image: '/images/products/plants/scindapsus-hanging.webp', category: 'plants' },
  { title: 'Scindapsus', image: '/images/products/plants/scindapsus.webp', category: 'plants' },
  { title: 'Song Of Jamaica', image: '/images/products/plants/song-of-gamaica.webp', category: 'plants' },
  { title: 'Song Of India', image: '/images/products/plants/song-of-india.webp', category: 'plants' },
  { title: 'Spathiphyllum Sensation', image: '/images/products/plants/spathiphyllum-sensation.webp', category: 'plants' },
  { title: 'Spathiphyllum', image: '/images/products/plants/spathiphyllum.webp', category: 'plants' },
  { title: 'Syngonium', image: '/images/products/plants/syngonium.webp', category: 'plants' },
  { title: 'Twisted Ficus', image: '/images/products/plants/twisted-ficus.webp', category: 'plants' },
  { title: 'Yucca Trunk', image: '/images/products/plants/yucca-trunk.webp', category: 'plants' },
  { title: 'Yucca', image: '/images/products/plants/yucca.webp', category: 'plants' },
  { title: 'Zamioculcus', image: '/images/products/plants/zamioculcus.webp', category: 'plants' },

  // 🪴 PLANTERS
    { title: 'Ali Baba Whitebrown Black', image: '/images/products/planters/ali-baba-whitebrown-black.webp', category: 'planters' },
  { title: 'Ali Baba', image: '/images/products/planters/ali-baba.webp', category: 'planters' },
  { title: 'Alibaba Ocean', image: '/images/products/planters/alibaba-ocean.webp', category: 'planters' },
  { title: 'Alibaba Ribbed Antique', image: '/images/products/planters/alibaba-ribbed-antique.webp', category: 'planters' },
  { title: 'Amphora Antique', image: '/images/products/planters/amphora-antique.webp', category: 'planters' },
  { title: 'Boat 2', image: '/images/products/planters/boat-2.webp', category: 'planters' },
  { title: 'Boat', image: '/images/products/planters/boat.webp', category: 'planters' },
  { title: 'Bowl Champagne', image: '/images/products/planters/bowl-champagne.webp', category: 'planters' },
  { title: 'Bowl Gold Silver Red Green Leaf', image: '/images/products/planters/bowl-gold-silver-red-green-leaf.webp', category: 'planters' },
  { title: 'Bowl Mother Of Pearl', image: '/images/products/planters/bowl-mother-of-paerl2.webp', category: 'planters' },
  { title: 'Bowl', image: '/images/products/planters/bowl.webp', category: 'planters' },
  { title: 'Broken Egg', image: '/images/products/planters/brocken-egg.webp', category: 'planters' },
  { title: 'Classic Abaca', image: '/images/products/planters/classic-abaca.webp', category: 'planters' },
  { title: 'Classic Bubbles', image: '/images/products/planters/classic-bubbles.webp', category: 'planters' },
  { title: 'Classic Hyacinth Light', image: '/images/products/planters/classic-hyacith-light.webp', category: 'planters' },
  { title: 'Classic Natural Pearl', image: '/images/products/planters/classic-natural-pearl.webp', category: 'planters' },
  { title: 'Classic Natural Rope', image: '/images/products/planters/classic-natural-rope.webp', category: 'planters' },
  { title: 'Classic Reflection', image: '/images/products/planters/classic-reflection.webp', category: 'planters' },
  { title: 'Classic Sparkle', image: '/images/products/planters/classic-sparkle.webp', category: 'planters' },
  { title: 'Classic Woody', image: '/images/products/planters/classic-woody.webp', category: 'planters' },
  { title: 'Classico Charcoal', image: '/images/products/planters/classico-charcol.webp', category: 'planters' },
  { title: 'Classico Gray', image: '/images/products/planters/classico-gray.webp', category: 'planters' },
  { title: 'Classico Silver', image: '/images/products/planters/classico-silver.webp', category: 'planters' },
  { title: 'Classico White', image: '/images/products/planters/classico-white.webp', category: 'planters' },
  { title: 'Classico', image: '/images/products/planters/classico.webp', category: 'planters' },
  { title: 'Coddler Synthetic', image: '/images/products/planters/coddler-synthetic.webp', category: 'planters' },
  { title: 'Coddler Chisel', image: '/images/products/planters/coddler-chisle.webp', category: 'planters' },
  { title: 'Coddler Polystone', image: '/images/products/planters/coddler-polystone.webp', category: 'planters' },
  { title: 'Coddler Wave Natural Black', image: '/images/products/planters/coddler-wave-natural-black.webp', category: 'planters' },
  { title: 'Coddler', image: '/images/products/planters/coddler.webp', category: 'planters' },
  { title: 'Conical Natural Rope', image: '/images/products/planters/conical-natural-rope.webp', category: 'planters' },
  { title: 'Conical', image: '/images/products/planters/conical.webp', category: 'planters' },
  { title: 'Cube Acacia', image: '/images/products/planters/cube-acacia.webp', category: 'planters' },
  { title: 'Cube', image: '/images/products/planters/cube.webp', category: 'planters' },
  { title: 'Cubico Brown', image: '/images/products/planters/cubico-brwn.webp', category: 'planters' },
  { title: 'Cubico Red', image: '/images/products/planters/cubico-red.webp', category: 'planters' },
  { title: 'Cubico White', image: '/images/products/planters/cubico-white.webp', category: 'planters' },
  { title: 'Cylindrical', image: '/images/products/planters/cylindrical.webp', category: 'planters' },
  { title: 'Cylindro 1', image: '/images/products/planters/cylindro-1.webp', category: 'planters' },
  { title: 'Cylindro High', image: '/images/products/planters/cylindro-high.webp', category: 'planters' },
  { title: 'Dewdrop Ocean', image: '/images/products/planters/dewdro-ocean.webp', category: 'planters' },
  { title: 'Dewdrop Wine Leaf', image: '/images/products/planters/dewdrop-wine-leaf-1.webp', category: 'planters' },
  { title: 'Egg Ocean', image: '/images/products/planters/egg-ocean.webp', category: 'planters' },
  { title: 'Elegant Square', image: '/images/products/planters/elegant-square.webp', category: 'planters' },
  { title: 'Ellipse Woody', image: '/images/products/planters/ellipse-woody-1.webp', category: 'planters' },
  { title: 'Fiberglass', image: '/images/products/planters/fiberglass.webp', category: 'planters' },
  { title: 'Fishbowl', image: '/images/products/planters/fishbowl.webp', category: 'planters' },
  { title: 'Globe', image: '/images/products/planters/globe-1.webp', category: 'planters' },
  { title: 'Goliath', image: '/images/products/planters/goliath-1.webp', category: 'planters' },
  { title: 'Harmonic', image: '/images/products/planters/harmonic.webp', category: 'planters' },
  { title: 'Highball Arabia', image: '/images/products/planters/highball-arabia.webp', category: 'planters' },
  { title: 'Highball Champagne', image: '/images/products/planters/highball-champagne.webp', category: 'planters' },
  { title: 'Highball Gold', image: '/images/products/planters/highball-gold.webp', category: 'planters' },
  { title: 'Highball Silver', image: '/images/products/planters/highball-silver.webp', category: 'planters' },
  { title: 'Lechuza Cubico', image: '/images/products/planters/lechuza-cubico.webp', category: 'planters' },
  { title: 'Rectangular', image: '/images/products/planters/rectangular.webp', category: 'planters' },
  { title: 'Teardrop', image: '/images/products/planters/teardrop.webp', category: 'planters' },
  { title: 'Wicker Square', image: '/images/products/planters/wicker-square.webp', category: 'planters' },
  { title: 'Wood Ring', image: '/images/products/planters/wood-ring.webp', category: 'planters' },

]