// /lib/products.ts

export type Product = {
  title: string
  image: string
  category: 'plants' | 'planters'
}

export const products: Product[] = [
  // 🌿 PLANTS
  { title: 'Aglaonema', image: '/images/products/plants/aglaonema.png', category: 'plants' },
  { title: 'Allocasia', image: '/images/products/plants/allocasia.png', category: 'plants' },
  { title: 'Anthurium', image: '/images/products/plants/anthurium.png', category: 'plants' },
  { title: 'Areca Palm', image: '/images/products/plants/areca-palm.png', category: 'plants' },
  { title: 'Aspidistra', image: '/images/products/plants/aspidistra.png', category: 'plants' },
  { title: 'Asplenium', image: '/images/products/plants/asplenium.png', category: 'plants' },
  { title: 'Buxus Microphylla', image: '/images/products/plants/buxus-microphylla.png', category: 'plants' },
  { title: 'Calathea Zebrina', image: '/images/products/plants/calatheazebrina.png', category: 'plants' },
  { title: 'Crassula', image: '/images/products/plants/crassula.png', category: 'plants' },
  { title: 'Croton Codium', image: '/images/products/plants/croton-codium.png', category: 'plants' },
  { title: 'Croton Finger', image: '/images/products/plants/croton-finger.png', category: 'plants' },
  { title: 'Croton Mix', image: '/images/products/plants/croton-mix.png', category: 'plants' },
  { title: 'Croton Petra', image: '/images/products/plants/croton-petra.png', category: 'plants' },
  { title: 'Cylindrical Ficus', image: '/images/products/plants/cylindrical-ficus.png', category: 'plants' },
  { title: 'Dracaena Compacta Branched', image: '/images/products/plants/dracaena-compacta-branched.png', category: 'plants' },
  { title: 'Dracaena Marginata Trunk', image: '/images/products/plants/dracaena-marginata-trunk.png', category: 'plants' },
  { title: 'Dracaena Marginata', image: '/images/products/plants/dracaena-marginata.png', category: 'plants' },
  { title: 'Dracaena Massangeana Trunk', image: '/images/products/plants/dracaena-massangeana-trunk.png', category: 'plants' },
  { title: 'Dracaena Massangeana', image: '/images/products/plants/dracaena-massangeana.png', category: 'plants' },
  { title: 'Dracaena Rikki', image: '/images/products/plants/dracaena-rikki.png', category: 'plants' },
  { title: 'Dracaena Warneckei', image: '/images/products/plants/dracaena-warneckei.png', category: 'plants' },
  { title: 'Ficus Alii', image: '/images/products/plants/ficus-alii.png', category: 'plants' },
  { title: 'Ficus Benjamina', image: '/images/products/plants/ficus-benjamina.png', category: 'plants' },
  { title: 'Ficus Bonsai', image: '/images/products/plants/ficus-bonsai.png', category: 'plants' },
  { title: 'Ficus Cyathstipula', image: '/images/products/plants/ficus-cyathstipula.png', category: 'plants' },
  { title: 'Ficus Elastica Variant', image: '/images/products/plants/ficus-elastica-2.png', category: 'plants' },
  { title: 'Ficus Elastica', image: '/images/products/plants/ficus-elastica.png', category: 'plants' },
  { title: 'Ficus Lyrata', image: '/images/products/plants/ficus-lyrata.png', category: 'plants' },
  { title: 'Ficus Robusta', image: '/images/products/plants/ficus-robusta.png', category: 'plants' },
  { title: 'Ficus Starlight', image: '/images/products/plants/ficus-starlight.png', category: 'plants' },
  { title: 'Gardenia', image: '/images/products/plants/gardenia.png', category: 'plants' },
  { title: 'Guzmania', image: '/images/products/plants/guzmania.png', category: 'plants' },
  { title: 'Imperial Red', image: '/images/products/plants/imperialred.png', category: 'plants' },
  { title: 'Kentia Palm', image: '/images/products/plants/kentia-palm.png', category: 'plants' },
  { title: 'Lemon Stripe Branch', image: '/images/products/plants/lemonstripe-branch.png', category: 'plants' },
  { title: 'Lemon Stripe', image: '/images/products/plants/lemonstripe.png', category: 'plants' },
  { title: 'Maria Christina', image: '/images/products/plants/maria-christina.png', category: 'plants' },
  { title: 'Monstera', image: '/images/products/plants/monstera.png', category: 'plants' },
  { title: 'Nephrolepsis', image: '/images/products/plants/nephrolepsis.png', category: 'plants' },
  { title: 'Nolina Trunk', image: '/images/products/plants/nolina-trunk.png', category: 'plants' },
  { title: 'Pachira', image: '/images/products/plants/pachira.png', category: 'plants' },
  { title: 'Phalaenopsis Purple', image: '/images/products/plants/phalaenopsis-purple.png', category: 'plants' },
  { title: 'Phalaenopsis White', image: '/images/products/plants/phalaenopsis-white.png', category: 'plants' },
  { title: 'Phoenix Palm', image: '/images/products/plants/phoneix-palm.png', category: 'plants' },
  { title: 'Rhapis Excelsa', image: '/images/products/plants/rhapis-excelsa.png', category: 'plants' },
  { title: 'Scandens', image: '/images/products/plants/scandens.png', category: 'plants' },
  { title: 'Schefflera Compacta', image: '/images/products/plants/schefflera-combacta.png', category: 'plants' },
  { title: 'Schefflera Gold Capella Netted', image: '/images/products/plants/schefflera-gold-capella-netted.png', category: 'plants' },
  { title: 'Schefflera Gold Capella', image: '/images/products/plants/schefflera-gold-capella.png', category: 'plants' },
  { title: 'Scindapsus Hanging', image: '/images/products/plants/scindapsus-hanging.png', category: 'plants' },
  { title: 'Scindapsus', image: '/images/products/plants/scindapsus.png', category: 'plants' },
  { title: 'Song Of Jamaica', image: '/images/products/plants/song-of-gamaica.png', category: 'plants' },
  { title: 'Song Of India', image: '/images/products/plants/song-of-india.png', category: 'plants' },
  { title: 'Spathiphyllum Sensation', image: '/images/products/plants/spathiphyllum-sensation.png', category: 'plants' },
  { title: 'Spathiphyllum', image: '/images/products/plants/spathiphyllum.png', category: 'plants' },
  { title: 'Syngonium', image: '/images/products/plants/syngonium.png', category: 'plants' },
  { title: 'Twisted Ficus', image: '/images/products/plants/twisted-ficus.png', category: 'plants' },
  { title: 'Yucca Trunk', image: '/images/products/plants/yucca-trunk.png', category: 'plants' },
  { title: 'Yucca', image: '/images/products/plants/yucca.png', category: 'plants' },
  { title: 'Zamioculcus', image: '/images/products/plants/zamioculcus.png', category: 'plants' },

  // 🪴 PLANTERS
    { title: 'Ali Baba Whitebrown Black', image: '/images/products/planters/ali-baba-whitebrown-black.png', category: 'planters' },
  { title: 'Ali Baba', image: '/images/products/planters/ali-baba.png', category: 'planters' },
  { title: 'Alibaba Ocean', image: '/images/products/planters/alibaba-ocean.png', category: 'planters' },
  { title: 'Alibaba Ribbed Antique', image: '/images/products/planters/alibaba-ribbed-antique.png', category: 'planters' },
  { title: 'Amphora Antique', image: '/images/products/planters/amphora-antique.png', category: 'planters' },
  { title: 'Boat 2', image: '/images/products/planters/boat-2.png', category: 'planters' },
  { title: 'Boat', image: '/images/products/planters/boat.png', category: 'planters' },
  { title: 'Bowl Champagne', image: '/images/products/planters/bowl-champagne.png', category: 'planters' },
  { title: 'Bowl Gold Silver Red Green Leaf', image: '/images/products/planters/bowl-gold-silver-red-green-leaf.png', category: 'planters' },
  { title: 'Bowl Mother Of Pearl', image: '/images/products/planters/bowl-mother-of-paerl2.png', category: 'planters' },
  { title: 'Bowl', image: '/images/products/planters/bowl.png', category: 'planters' },
  { title: 'Broken Egg', image: '/images/products/planters/brocken-egg.png', category: 'planters' },
  { title: 'Classic Abaca', image: '/images/products/planters/classic-abaca.png', category: 'planters' },
  { title: 'Classic Bubbles', image: '/images/products/planters/classic-bubbles.png', category: 'planters' },
  { title: 'Classic Hyacinth Light', image: '/images/products/planters/classic-hyacith-light.png', category: 'planters' },
  { title: 'Classic Natural Pearl', image: '/images/products/planters/classic-natural-pearl.png', category: 'planters' },
  { title: 'Classic Natural Rope', image: '/images/products/planters/classic-natural-rope.png', category: 'planters' },
  { title: 'Classic Reflection', image: '/images/products/planters/classic-reflection.png', category: 'planters' },
  { title: 'Classic Sparkle', image: '/images/products/planters/classic-sparkle.png', category: 'planters' },
  { title: 'Classic Woody', image: '/images/products/planters/classic-woody.png', category: 'planters' },
  { title: 'Classico Charcoal', image: '/images/products/planters/classico-charcol.png', category: 'planters' },
  { title: 'Classico Gray', image: '/images/products/planters/classico-gray.png', category: 'planters' },
  { title: 'Classico Silver', image: '/images/products/planters/classico-silver.png', category: 'planters' },
  { title: 'Classico White', image: '/images/products/planters/classico-white.png', category: 'planters' },
  { title: 'Classico', image: '/images/products/planters/classico.png', category: 'planters' },
  { title: 'Coddler Synthetic', image: '/images/products/planters/coddler-synthetic.png', category: 'planters' },
  { title: 'Coddler Chisel', image: '/images/products/planters/coddler-chisle.png', category: 'planters' },
  { title: 'Coddler Polystone', image: '/images/products/planters/coddler-polystone.png', category: 'planters' },
  { title: 'Coddler Wave Natural Black', image: '/images/products/planters/coddler-wave-natural-black.png', category: 'planters' },
  { title: 'Coddler', image: '/images/products/planters/coddler.png', category: 'planters' },
  { title: 'Conical Natural Rope', image: '/images/products/planters/conical-natural-rope.png', category: 'planters' },
  { title: 'Conical', image: '/images/products/planters/conical.png', category: 'planters' },
  { title: 'Cube Acacia', image: '/images/products/planters/cube-acacia.png', category: 'planters' },
  { title: 'Cube', image: '/images/products/planters/cube.png', category: 'planters' },
  { title: 'Cubico Brown', image: '/images/products/planters/cubico-brwn.png', category: 'planters' },
  { title: 'Cubico Red', image: '/images/products/planters/cubico-red.png', category: 'planters' },
  { title: 'Cubico White', image: '/images/products/planters/cubico-white.png', category: 'planters' },
  { title: 'Cylindrical', image: '/images/products/planters/cylindrical.png', category: 'planters' },
  { title: 'Cylindro 1', image: '/images/products/planters/cylindro-1.png', category: 'planters' },
  { title: 'Cylindro High', image: '/images/products/planters/cylindro-high.png', category: 'planters' },
  { title: 'Dewdrop Ocean', image: '/images/products/planters/dewdro-ocean.png', category: 'planters' },
  { title: 'Dewdrop Wine Leaf', image: '/images/products/planters/dewdrop-wine-leaf-1.png', category: 'planters' },
  { title: 'Egg Ocean', image: '/images/products/planters/egg-ocean.png', category: 'planters' },
  { title: 'Elegant Square', image: '/images/products/planters/elegant-square.png', category: 'planters' },
  { title: 'Ellipse Woody', image: '/images/products/planters/ellipse-woody-1.png', category: 'planters' },
  { title: 'Fiberglass', image: '/images/products/planters/fiberglass.png', category: 'planters' },
  { title: 'Fishbowl', image: '/images/products/planters/fishbowl.png', category: 'planters' },
  { title: 'Globe', image: '/images/products/planters/globe-1.png', category: 'planters' },
  { title: 'Goliath', image: '/images/products/planters/goliath-1.png', category: 'planters' },
  { title: 'Harmonic', image: '/images/products/planters/harmonic.png', category: 'planters' },
  { title: 'Highball Arabia', image: '/images/products/planters/highball-arabia.png', category: 'planters' },
  { title: 'Highball Champagne', image: '/images/products/planters/highball-champagne.png', category: 'planters' },
  { title: 'Highball Gold', image: '/images/products/planters/highball-gold.png', category: 'planters' },
  { title: 'Highball Silver', image: '/images/products/planters/highball-silver.png', category: 'planters' },
  { title: 'Lechuza Cubico', image: '/images/products/planters/lechuza-cubico.png', category: 'planters' },
  { title: 'Rectangular', image: '/images/products/planters/rectangular.png', category: 'planters' },
  { title: 'Teardrop', image: '/images/products/planters/teardrop.png', category: 'planters' },
  { title: 'Wicker Square', image: '/images/products/planters/wicker-square.png', category: 'planters' },
  { title: 'Wood Ring', image: '/images/products/planters/wood-ring.png', category: 'planters' },

]